### ISSUE TITLE
Failed to load Attention Layers

### ISSUE THREAD

**Issue by raviy0807** [SYLan2019/Transformer-Gan-Anomaly-Detection#1]
while training, i getting following error. Seems like file is missing : 

Transformer-Gan-Anomaly-Detection/lib/models/unet_parts.py", line 6, in <module>
    from .fcanet import MultiSpectralAttentionLayer
ModuleNotFoundError: No module named 'lib.models.fcanet'

**Comment by ycycse** [comment]
Hi, thank you for pointing out that.
It was a mistake, you can directly delete the MultiSpectralAttentionLayer in code, because it's just for experiment. I'll fix the code in repo later.
